version: "3"

services:
  _:
    &default
    image: ""
    stop_grace_period: 1s
    tty: true
    stdin_open: true
  _compile:
    image: golang
    entrypoint: go
    command: "build -o /build/ lib/dockerized.go"
    working_dir: /src
    volumes:
      - ".:/src"
      - "./build:/build"
      - "dockerized_compile:/go/pkg"
  alpine:
    &alpine
    <<: *default
    image: "alpine_${ALPINE_VERSION}"
    build:
      context: apps/alpine
      args:
        ALPINE_VERSION: "${ALPINE_VERSION}"
        ALPINE_PACKAGES: "tree"
  aws:
    <<: *default
    image: "amazon/aws-cli:${AWS_VERSION}"
    volumes:
      - "${HOME}/.aws:/root/.aws"
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID:-}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY:-}"
  doctl:
    <<: *default
    image: "doctl:${DOCTL_VERSION}"
    build:
      context: apps/doctl
      dockerfile: ../alpine/Dockerfile
      args:
        ALPINE_VERSION: "${ALPINE_VERSION}"
        BUILD_SCRIPT_ARGS: "${DOCTL_VERSION}"
    entrypoint: [ "doctl" ]
    volumes:
      - "${HOME}/.dockerized/apps/doctl:/root"
  dotnet:
    <<: *default
    image: "mcr.microsoft.com/dotnet/sdk:${DOTNET_VERSION}-alpine"
    entrypoint: [ "dotnet" ]
  gh:
    <<: *default
    image: "gh:${GH_VERSION}"
    build:
      context: apps/gh
      dockerfile: ../alpine/Dockerfile
      args:
        ALPINE_VERSION: "${ALPINE_VERSION}"
        ALPINE_PACKAGES: "git openssh-client"
        BUILD_SCRIPT_ARGS: "${GH_VERSION}"
    entrypoint: [ "/init.sh", "/gh/bin/gh" ]
    volumes:
      - "${HOME}/.dockerized/apps/gh:/root"
      - "./apps/gh/init.sh:/init.sh"
    environment:
      BROWSER: "echo"
  git:
    <<: *default
    image: "alpine/git:v${GIT_VERSION}"
    entrypoint: [ "git" ]
  go:
    <<: *default
    image: "golang:${GO_VERSION}"
    entrypoint: [ "go" ]
  helm:
    <<: *default
    image: "alpine/helm:${HELM_VERSION}"
  http:
    <<: *default
    image: "alpine/httpie:${HTTPIE_VERSION}"
    entrypoint: [ "http" ]
  jq:
    <<: *default
    image: stedolan/jq
  node:
    &node
    <<: *default
    image: "node:${NODE_VERSION}"
    entrypoint: [ "node" ]
    volumes:
      - "node_modules:/usr/local/lib/node_modules"
      - "${HOME}/.dockerized/apps/node:/root"
  npm:
    <<: *node
    entrypoint: [ "npm" ]
  npx:
    <<: *node
    entrypoint: [ "npx" ]
  php:
    <<: *default
    image: "php:${PHP_VERSION}"
  protoc:
    <<: *default
    image: "protoc:${PROTOC_VERSION}"
    build:
      context: apps/protoc
      args:
        PROTOC_VERSION: "${PROTOC_VERSION}"
        PROTOC_BASE: "${PROTOC_BASE}"
        PROTOC_ARCH: "${PROTOC_ARCH}"
  python:
    &python
    <<: *default
    image: "python:${PYTHON_VERSION}"
    entrypoint: [ "python" ]
    volumes:
      - "python_modules:/usr/local/lib/python${PYTHON_VERSION}/site-packages"
  python2:
    <<: *default
    image: "python:${PYTHON2_VERSION}"
  pip:
    <<: *python
    entrypoint: [ "pip" ]
  ruby:
    <<: *default
    image: "ruby:${RUBY_VERSION}"
    entrypoint: [ "ruby" ]
  s3cmd:
    <<: *default
    build:
      context: apps/s3cmd
      args:
        S3CMD_VERSION: "${S3CMD_VERSION}"
        S3CMD_BASE: "${S3CMD_BASE}"
    image: "s3cmd:${S3CMD_VERSION}"
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID:-}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY:-}"
    volumes:
      - "${HOME}/.dockerized/apps/s3cmd:/root"
  swagger-codegen:
    <<: *default
    image: "swaggerapi/swagger-codegen-cli-v3:${SWAGGER_CODEGEN_VERSION}"
  tree:
    <<: *alpine
    entrypoint: [ "tree" ]
  tsc:
    <<: *node
    entrypoint: [ "npx", "--package=typescript@${TSC_VERSION}", "tsc" ]
  vue:
    <<: *node
    entrypoint: [ "npx", "--package=@vue/cli@${VUE_VERSION}", "vue" ]
  wget:
    <<: *default
    image: "${DEFAULT_BASE}"
    entrypoint: [ "wget" ]
  yarn:
    <<: *node
    entrypoint: [ "yarn" ]
volumes:
  node_modules: {}
  python_modules: {}
  pip_cache: {}
  dockerized_compile: {}
