version: "3"

services:
  _compile:
    image: golang
    entrypoint: go
    command: "build -o /build/ lib/dockerized.go"
    working_dir: /src
    volumes:
      - ".:/src"
      - "./build:/build"
      - "dockerized_compile:/go/pkg"
  alpine:
    &alpine
    image: "alpine_${ALPINE_VERSION}"
    build:
      context: apps/alpine
      args:
        ALPINE_VERSION: "${ALPINE_VERSION}"
        ALPINE_PACKAGES: "tree"
  ab:
    <<: *alpine
    build:
      context: apps/alpine
      args:
        ALPINE_VERSION: "${ALPINE_VERSION}"
        ALPINE_PACKAGES: "apache2-ssl apache2-utils ca-certificates"
    entrypoint: [ "ab" ]
  aws:
    image: "amazon/aws-cli:${AWS_VERSION}"
    volumes:
      - "${HOME:-}/.aws:/root/.aws"
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID:-}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY:-}"
  bash:
    image: "bash"
    build:
      context: apps/alpine
      args:
        ALPINE_VERSION: "${ALPINE_VERSION}"
        ALPINE_PACKAGES: "bash"
    entrypoint: ["/bin/bash"]
  doctl:
    image: "doctl:${DOCTL_VERSION}"
    build:
      context: apps/doctl
      dockerfile: ../alpine/Dockerfile
      args:
        ALPINE_VERSION: "${ALPINE_VERSION}"
        BUILD_SCRIPT_ARGS: "${DOCTL_VERSION}"
    entrypoint: [ "doctl" ]
    volumes:
      - "${HOME:-}/.dockerized/apps/doctl:/root"
  dotnet:
    image: "mcr.microsoft.com/dotnet/sdk:${DOTNET_VERSION}-alpine"
    entrypoint: [ "dotnet" ]
  gh:
    image: "gh:${GH_VERSION}"
    build:
      context: apps/gh
      dockerfile: ../alpine/Dockerfile
      args:
        ALPINE_VERSION: "${ALPINE_VERSION}"
        ALPINE_PACKAGES: "git openssh-client"
        BUILD_SCRIPT_ARGS: "${GH_VERSION}"
    entrypoint: [ "/init.sh", "/gh/bin/gh" ]
    volumes:
      - "${HOME:-}/.dockerized/apps/gh:/root"
      - "./apps/gh/init.sh:/init.sh"
    environment:
      BROWSER: "echo"
  git:
    image: "alpine/git:v${GIT_VERSION}"
    entrypoint: [ "git" ]
  go:
    image: "golang:${GO_VERSION}"
    entrypoint: [ "go" ]
    volumes:
      - "go_cache:/go/pkg"
    environment:
      GOOS: "${GOOS:-}"
      GOARCH: "${GOARCH:-}"
  helm:
    image: "alpine/helm:${HELM_VERSION}"
  http:
    image: "alpine/httpie:${HTTPIE_VERSION}"
    entrypoint: [ "http" ]
  java:
    image: "openjdk:${JAVA_VERSION}"
    entrypoint: [ "java" ]
  jq:
    image: stedolan/jq
  lua:
    image: "${LUA_IMAGE}:${LUA_VERSION}"
    entrypoint: [ "lua" ]
  node:
    &node
    image: "node:${NODE_VERSION}"
    entrypoint: [ "node" ]
    volumes:
      - "node_modules:/usr/local/lib/node_modules"
      - "${HOME:-}/.dockerized/apps/node:/root"
  npm:
    <<: *node
    entrypoint: [ "npm" ]
  npx:
    <<: *node
    entrypoint: [ "npx" ]
  perl:
    image: perl:${PERL_VERSION}
    entrypoint: [ "perl" ]
  php:
    image: "php:${PHP_VERSION}"
  protoc:
    image: "protoc:${PROTOC_VERSION}"
    build:
      context: apps/protoc
      args:
        PROTOC_VERSION: "${PROTOC_VERSION}"
        PROTOC_BASE: "${PROTOC_BASE}"
        PROTOC_ARCH: "${PROTOC_ARCH}"
  python:
    &python
    image: "python:${PYTHON_VERSION}"
    entrypoint: [ "python" ]
    volumes:
      - "python_modules:/usr/local/lib/python${PYTHON_VERSION}/site-packages"
      - "${HOME:-}/.dockerized/apps/python:/root"
  python2:
    image: "python:${PYTHON2_VERSION}"
  pip:
    <<: *python
    entrypoint: [ "pip" ]
  ruby:
    image: "ruby:${RUBY_VERSION}"
    entrypoint: [ "ruby" ]
  rustc:
    image: "rust:${RUST_VERSION}"
    entrypoint: [ "rustc" ]
  s3cmd:
    build:
      context: apps/s3cmd
      args:
        S3CMD_VERSION: "${S3CMD_VERSION}"
        S3CMD_BASE: "${S3CMD_BASE}"
    image: "s3cmd:${S3CMD_VERSION}"
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID:-}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY:-}"
    volumes:
      - "${HOME:-}/.dockerized/apps/s3cmd:/root"
#  semantic-release-cli:
#    <<: *node
#    entrypoint: [ "npx", "--package=semantic-release-cli@${SEMANTIC_RELEASE_VERSION}", "semantic-release-cli" ]
#    volumes:
#      - "${HOME:-}/.dockerized/apps/gh:/root"
  swagger-codegen:
    image: "swaggerapi/swagger-codegen-cli-v3:${SWAGGER_CODEGEN_VERSION}"
  tree:
    <<: *alpine
    entrypoint: [ "tree" ]
  tsc:
    <<: *node
    entrypoint: [ "npx", "--package=typescript@${TSC_VERSION}", "tsc" ]
  vue:
    <<: *node
    entrypoint: [ "npx", "--package=@vue/cli@${VUE_VERSION}", "vue" ]
  wget:
    image: "${DEFAULT_BASE}"
    entrypoint: [ "wget" ]
  yarn:
    <<: *node
    entrypoint: [ "yarn" ]
  zip:
    image: "zip"
    build:
      context: apps/alpine
      args:
        ALPINE_VERSION: "${ALPINE_VERSION}"
        ALPINE_PACKAGES: "zip"
    entrypoint: ["/usr/bin/zip"]

volumes:
  node_modules: {}
  python_modules: {}
  pip_cache: {}
  dockerized_compile: {}
  go_cache: {}
