name: Release
on:
  push:
    branches:
      - master
      - feature/semantic-release-build
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - { name: windows64, GOOS: windows, GOARCH: amd64, BIN: "dockerized.exe" }
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p release/${{ matrix.target.name }}
      - name: Copy static assets
        run: cp -r apps/ .env *.md release/${{ matrix.target.name }}
      - name: Build
        env:
          GOOS: "${{ matrix.target.GOOS }}"
          BIN: "${{ matrix.target.BIN }}"
          GO_VERSION: "1.17.8"
        run: |
          bin/dockerized go build -o release/${{ matrix.target.name }}/bin/$BIN lib/dockerized.go
      - name: Zip
        working-directory: release/${{ matrix.target.name }}
        run: |
          zip -r $GITHUB_WORKSPACE/release/${{ matrix.target.name }}.zip *
      - uses: actions/upload-artifact@v2
        with:
          name: release
          path: release/*.zip
  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: release
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx -p @semantic-release/changelog -p @semantic-release/git -p semantic-release semantic-release --dry-run