name: Compile and Test
on: [push]

jobs:
  CompileAndTest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2022, macos-10.15]
      max-parallel: 1
      fail-fast: true
    steps:
      # region mac
      - name: Install Docker
        if:  runner.os == 'macOS'
        uses: docker-practice/actions-setup-docker@master
      # endregion

      - name: Checkout Dockerized
        uses: actions/checkout@v2

      # region windows
      - if: runner.os == 'windows'
        shell: bash
        run: bin/dockerized --compile
      - if: runner.os == 'windows'
        shell: cmd
        run: bin/dockerized --compile
      # endregion

      - run: bin/dockerized --compile --help
      - run: bin/dockerized go version